### ISSUE TITLE
Can you add MJ12bot

### ISSUE THREAD

**Issue by UiharuKazari2008** [mariusv/nginx-badbot-blocker#27]
I cant seem to find a way to block the MJ12bot from my server. I currently am trying to keep my sites off all search engines to keep them "word of mouth"
Not to mention it tries non stop to access admin pages

**Comment by UiharuKazari2008** [comment]
The user agent used is Mozilla/5.0 (compatible; MJ12bot/v1.4.7; http://mj12bot.com/)

**Comment by mitchellkrogza** [comment]
Have sent a PR through for this.

**Comment by mariusv** [comment]
This has been fixed with PR #28 . Thank you @mitchellkrogza

**Comment by UiharuKazari2008** [comment]
![capture1076](https://cloud.githubusercontent.com/assets/15165770/21812450/f986c962-d720-11e6-9529-a205f624a2b4.png)
Its still getting trough some how, works on every other bot except MJ12 they always find a way trough. Cant do IP ban sense its a dynamic distributed crawer

**Comment by mitchellkrogza** [comment]
Have sent a PR with a correction to the Regex. Try again once Marius merges it and make sure to reload Nginx.
